### PR TITLE
Reporting and Administration

### PR DESCRIPTION
**Pull request by DSollick**
Add the ability to report pages and a basic admin panel to administer those reports.

### CODE REVIEW

**Comment by DHowett** [comment]
Generally good, but I think we should address some of the above concerns and look at using POST for the data destruction endpoints.

**Comment by Hekter** [comment]
Refactored variable names to be of more consistent style. Somehow getting a syntax error on go build and goimports in report.go lines 82 and 91 despite there being no discernible change from d977e4a to 1e3a9e4.

**Comment by DHowett** [comment]
I have reordered some of the commits leading up to there. You'll need to rebase your changes (which I will show you :P)

**Comment by Hekter** [comment]
/admin is still looking very ugly and is in sincere need of proper CSS styling but the rest of the backend should be done and to Ghostbin project specs. Hopefully. :)

**Comment by khionu** [comment]
How can I access the administration panel?

**Comment by resynth1943** [comment]
@khionu It *was* for administrators only :)

**Comment by DHowett** [comment]
It’s cool that you’re doing this, but surprising that you’re floating
around already-closed four-year-old pull requests on an abandoned project.

**Comment by resynth1943** [comment]
@DHowett Kinda leaving my mark. Know when dogs piss on a spot? Yeah. Also, I know khionu :)

**Comment by khionu** [comment]
Sorry, I don't know you, don't drag me into your drama.

**Comment by resynth1943** [comment]
@khionu lol ok, whatever you say 😂

**Pull request merged**
